// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: template.proto

#ifndef PROTOBUF_template_2eproto__INCLUDED
#define PROTOBUF_template_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Image.pb.h"
#include "rslam.pb.h"
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_template_2eproto();
void protobuf_AssignDesc_template_2eproto();
void protobuf_ShutdownFile_template_2eproto();

class TemplateMsg;
class TemplateCorpusMsg;

// ===================================================================

class TemplateMsg : public ::google::protobuf::Message {
 public:
  TemplateMsg();
  virtual ~TemplateMsg();

  TemplateMsg(const TemplateMsg& from);

  inline TemplateMsg& operator=(const TemplateMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TemplateMsg& default_instance();

  void Swap(TemplateMsg* other);

  // implements Message ----------------------------------------------

  TemplateMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TemplateMsg& from);
  void MergeFrom(const TemplateMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .pb.ReferenceFrameIdMsg id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline const ::pb::ReferenceFrameIdMsg& id() const;
  inline ::pb::ReferenceFrameIdMsg* mutable_id();
  inline ::pb::ReferenceFrameIdMsg* release_id();
  inline void set_allocated_id(::pb::ReferenceFrameIdMsg* id);

  // optional .pb.ImageMsg image = 2;
  inline bool has_image() const;
  inline void clear_image();
  static const int kImageFieldNumber = 2;
  inline const ::pb::ImageMsg& image() const;
  inline ::pb::ImageMsg* mutable_image();
  inline ::pb::ImageMsg* release_image();
  inline void set_allocated_image(::pb::ImageMsg* image);

  // @@protoc_insertion_point(class_scope:pb.TemplateMsg)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_image();
  inline void clear_has_image();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::pb::ReferenceFrameIdMsg* id_;
  ::pb::ImageMsg* image_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_template_2eproto();
  friend void protobuf_AssignDesc_template_2eproto();
  friend void protobuf_ShutdownFile_template_2eproto();

  void InitAsDefaultInstance();
  static TemplateMsg* default_instance_;
};
// -------------------------------------------------------------------

class TemplateCorpusMsg : public ::google::protobuf::Message {
 public:
  TemplateCorpusMsg();
  virtual ~TemplateCorpusMsg();

  TemplateCorpusMsg(const TemplateCorpusMsg& from);

  inline TemplateCorpusMsg& operator=(const TemplateCorpusMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TemplateCorpusMsg& default_instance();

  void Swap(TemplateCorpusMsg* other);

  // implements Message ----------------------------------------------

  TemplateCorpusMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TemplateCorpusMsg& from);
  void MergeFrom(const TemplateCorpusMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pb.TemplateMsg place = 1;
  inline int place_size() const;
  inline void clear_place();
  static const int kPlaceFieldNumber = 1;
  inline const ::pb::TemplateMsg& place(int index) const;
  inline ::pb::TemplateMsg* mutable_place(int index);
  inline ::pb::TemplateMsg* add_place();
  inline const ::google::protobuf::RepeatedPtrField< ::pb::TemplateMsg >&
      place() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb::TemplateMsg >*
      mutable_place();

  // @@protoc_insertion_point(class_scope:pb.TemplateCorpusMsg)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::pb::TemplateMsg > place_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_template_2eproto();
  friend void protobuf_AssignDesc_template_2eproto();
  friend void protobuf_ShutdownFile_template_2eproto();

  void InitAsDefaultInstance();
  static TemplateCorpusMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// TemplateMsg

// optional .pb.ReferenceFrameIdMsg id = 1;
inline bool TemplateMsg::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TemplateMsg::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TemplateMsg::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TemplateMsg::clear_id() {
  if (id_ != NULL) id_->::pb::ReferenceFrameIdMsg::Clear();
  clear_has_id();
}
inline const ::pb::ReferenceFrameIdMsg& TemplateMsg::id() const {
  return id_ != NULL ? *id_ : *default_instance_->id_;
}
inline ::pb::ReferenceFrameIdMsg* TemplateMsg::mutable_id() {
  set_has_id();
  if (id_ == NULL) id_ = new ::pb::ReferenceFrameIdMsg;
  return id_;
}
inline ::pb::ReferenceFrameIdMsg* TemplateMsg::release_id() {
  clear_has_id();
  ::pb::ReferenceFrameIdMsg* temp = id_;
  id_ = NULL;
  return temp;
}
inline void TemplateMsg::set_allocated_id(::pb::ReferenceFrameIdMsg* id) {
  delete id_;
  id_ = id;
  if (id) {
    set_has_id();
  } else {
    clear_has_id();
  }
}

// optional .pb.ImageMsg image = 2;
inline bool TemplateMsg::has_image() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TemplateMsg::set_has_image() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TemplateMsg::clear_has_image() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TemplateMsg::clear_image() {
  if (image_ != NULL) image_->::pb::ImageMsg::Clear();
  clear_has_image();
}
inline const ::pb::ImageMsg& TemplateMsg::image() const {
  return image_ != NULL ? *image_ : *default_instance_->image_;
}
inline ::pb::ImageMsg* TemplateMsg::mutable_image() {
  set_has_image();
  if (image_ == NULL) image_ = new ::pb::ImageMsg;
  return image_;
}
inline ::pb::ImageMsg* TemplateMsg::release_image() {
  clear_has_image();
  ::pb::ImageMsg* temp = image_;
  image_ = NULL;
  return temp;
}
inline void TemplateMsg::set_allocated_image(::pb::ImageMsg* image) {
  delete image_;
  image_ = image;
  if (image) {
    set_has_image();
  } else {
    clear_has_image();
  }
}

// -------------------------------------------------------------------

// TemplateCorpusMsg

// repeated .pb.TemplateMsg place = 1;
inline int TemplateCorpusMsg::place_size() const {
  return place_.size();
}
inline void TemplateCorpusMsg::clear_place() {
  place_.Clear();
}
inline const ::pb::TemplateMsg& TemplateCorpusMsg::place(int index) const {
  return place_.Get(index);
}
inline ::pb::TemplateMsg* TemplateCorpusMsg::mutable_place(int index) {
  return place_.Mutable(index);
}
inline ::pb::TemplateMsg* TemplateCorpusMsg::add_place() {
  return place_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::TemplateMsg >&
TemplateCorpusMsg::place() const {
  return place_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb::TemplateMsg >*
TemplateCorpusMsg::mutable_place() {
  return &place_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_template_2eproto__INCLUDED
